#!/bin/csh -f

echo aaa > ~/aaa
hostname

source /group/clas12/packages/setup.csh
module load clas12/pro


# Usage:
# go_simulate gcard TITLE workdir nevents

set launchd  = $1
set workdir  = $2
set SIMU     = $3
set gcard    = $4
set NEVENTS  = $5
set TITLE    = $6
echo

set dir = $workdir/$TITLE
mkdir -p $dir
mkdir -p $dir/gemc
mkdir -p $dir/root
mkdir -p $dir/log
set simu = `printf "%05d" $SIMU`

set origd = `pwd`

# Look for first non existing dir
		echo Starting Simulation $SIMU
		echo output directory is $dir
		echo

		cp -r $launchd/dc__bank.txt .

		echo gemc executable: `which gemc`
		echo
		ls -alp  
		echo    
		
		echo gemc experiment directory set to $GEMC_DATA_DIR
		echo       

		echo Getting run conditions from gcard
		set runno = `grep RUNNO $gcard | awk -F \" '{print $4}'`
		set torus = `grep SCALE_FIELD $gcard | grep TorusSymmetric | awk -F\" '{print $4}' | awk -F, '{print $2}'`		
		set solen = `grep SCALE_FIELD $gcard | grep solenoid | awk -F\" '{print $4}' | awk -F, '{print $2}'`		
		echo run number  is $runno
		echo torus field is $torus
		echo solenoid field is $solen

		echo Running gemc
		/w/hallb-scifs17exp/clas12/users/sergeyeva/test/adapted_to_ALERT/source/gemc $gcard -N=$NEVENTS -USE_GUI=0 -PRINT_EVENT=5 > $dir/log/gemc_$simu.log
		# /w/hallb-scifs17exp/clas12/users/sergeyeva/gemc_source_exec/source/gemc $gcard -N=$NEVENTS -USE_GUI=0 -PRINT_EVENT=5 > $dir/log/gemc_$simu.log

		module switch clas12/2.0
		evio2root -B=dc -INPUTF=gemc_10events_650nA_LUMI.ev

                ls -l
		
		mv gemc_10events_650nA_LUMI.ev        $dir/gemc/gemc_10events_650nA_LUMI_$simu.evio
		mv gemc_10events_650nA_LUMI.root      $dir/root/gemc_10events_650nA_LUMI_$simu.root


