#!/bin/csh -f

set TITLE    = ( clas12-nodisk       )
set gcard    = ( clas12-nodisk.gcard ) 
set NEVENTS  = 5
set NMAX     = 500

set launchd   = `pwd`
set workdir   = /work/clas12/users/sergeyeva/LUMI_650nA_totalALERTsetup_11dec2020
set gcard_dir = .
#set exp_dir   = /group/clas12/gemc/4.4.1

set i = 1
while ($i <= $NMAX)

	set simu = $i
	set w = 1

	while ($w <= $#TITLE)
		rm -f gemc.jsub
		\echo  JOBNAME: $TITLE[$w]_$i                                                                    > gemc.jsub
		\echo  PROJECT: clas12                                                                          >> gemc.jsub
		\echo  MAIL:    sergeyeva@ipno.in2p3.fr                                                                 >> gemc.jsub
		\echo  TRACK:   simulation                                                                      >> gemc.jsub
#		\echo  TRACK:   debug                                                                           >> gemc.jsub
		\echo  COMMAND: go_simulate $launchd $workdir $simu $gcard[$w] $NEVENTS $TITLE[$w]              >> gemc.jsub
		\echo  OS:      general                                               		                >> gemc.jsub
		\echo  MEMORY:  1500 MB                                         		                >> gemc.jsub
                \echo  TIME:    1440                                                                             >> gemc.jsub
		\echo  OTHER_FILES: $launchd/go_simulate                                                        >> gemc.jsub
		\echo  OTHER_FILES: $launchd/$gcard_dir/$gcard[$w]                                              >> gemc.jsub
		\echo
		\echo Launching simulation $i for $TITLE[$w]
		\echo
		jsub gemc.jsub
		#/site/bin/jsub gemc.jsub
		#      cat  gemc.jsub
		@ w += 1
	end 
	@ i += 1 
end


