#!/bin/csh -f

echo aaa > ~/aaa
hostname

source /group/clas12/packages/setup.csh
module load clas12/pro


# Usage:
# go_simulate gcard TITLE workdir nevents

set launchd  = $1
set workdir  = $2
set coatdir  = $3
set SIMU     = $4
set gcard    = $5
set NEVENTS  = $6
set TITLE    = $7
echo

which java 
java -version
module avail

# set coat environment
echo COATJAVA set to $COATJAVA
echo

set dir = $workdir/$TITLE
mkdir -p $dir
mkdir -p $dir/gemc
#mkdir -p $dir/root
mkdir -p $dir/decoded
mkdir -p $dir/cooked
mkdir -p $dir/log
set simu = `printf "%05d" $SIMU`

set origd = `pwd`

# Look for first non existing dir
		echo Starting Simulation $SIMU
		echo output directory is $dir
		echo


		echo gemc executable: `which gemc`
		echo
		ls -alp  
		echo    
		
		echo Getting run conditions from gcard
		set runno = `grep RUNNO $gcard | awk -F \" '{print $4}'`
		set torus = `grep SCALE_FIELD $gcard | grep TorusSymmetric | awk -F\" '{print $4}' | awk -F, '{print $2}'`		
		set solen = `grep SCALE_FIELD $gcard | grep newSolenoid | awk -F\" '{print $4}' | awk -F, '{print $2}'`		
		echo run number  is $runno
		echo torus field is $torus
		echo solenoid field is $solen

		echo Running gemc
		/w/hallb-scifs17exp/clas12/users/sergeyeva/test/adapted_to_ALERT/source/gemc $gcard -N=$NEVENTS -USE_GUI=0 -PRINT_EVENT=10 > $dir/log/gemc_$simu.log
#		evio2root -B=ft -INPUTF=out.ev
		echo Running evio2hipo
	        $coatdir/bin/evio2hipo -r $runno -t $torus -s $solen -i out.ev -o out.hipo > $dir/log/rec_$simu.log
		echo Running reconstruction
		$coatdir/bin/recon-util -i out.hipo -o out.rec.hipo -c 2  -y clas12-default.yaml >> $dir/log/rec_$simu.log

                ls -l
		
		mv out.ev        $dir/gemc/out_$simu.evio
#		mv out.root      $dir/root/out_$simu.root
		mv out.hipo      $dir/decoded/out_$simu.hipo
                mv out.rec.hipo  $dir/cooked/out_$simu.rec.hipo


